import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const classNames = cn(inter.className, 'w-full max-w-5xl')

  return (
    <html
      lang="en"
      className="box-border flex w-full justify-center object-center"
    >
      <body className={classNames}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
